---
- name: Deploy PHP Application
  hosts: all
  become: yes

  tasks:
    - name: Copy Docker Compose file to target host
      copy:
        src: /path/to/your/docker-compose.yml
        dest: /path/on/target/host/docker-compose.yml

    - name: Start Docker Compose
      command: docker-compose -f /path/on/target/host/docker-compose.yml up -d
