---
- name: Deploy PHP Application
  hosts: webserver
  become: yes

  tasks:
    - name: Copy Docker Compose file to target host
      copy:
        src: /ProjetDevops/docker-compose.yml
        dest: /ProjetDevops/docker-compose.yml

    - name: Start Docker Compose
      command: docker-compose -f /ProjetDevops/docker-compose.yml up -d