---
- hosts: localhost
  tasks:
    - name: Clone Symfony code from Git
      git:
        repo: https://github.com/salmakacem1999/ProjetDevops.git
        dest: /var/www/ProjetDevops
        update: yes

    - name: Install Composer dependencies
      command: composer install --no-interaction --working-dir=/var/www/ProjetDevops

    - name: Set up Symfony parameters
      template:
        src: parameters.yml.j2
        dest: /var/www/ProjetDevops/app/config/parameters.yml
      when: not skip_parameters

    - name: Update Nginx configuration for Symfony
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/symfony
        notify: Restart Nginx

